language: node_js
node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && node_modules/.bin/serverless deploy --stage=dev  --verbose
  - test $TRAVIS_TAG && node_modules/.bin/serverless deploy --stage=prod --verbose
