service: ilios-lti-launch

custom:
  ltiDashboard-dev: 'https://d4jps70wc8ppm.cloudfront.net'
  ltiDashboard-prod: 'https://lti-dashboard.iliosproject.org'
  additionalStacks:
    permanent:
      Resources:
        S3BucketData:
          Type: AWS::S3::Bucket
          Properties:
            BucketName: ${self:provider.environment.CONFIG_BUCKET}
            AccessControl: Private
          DeletionPolicy : Retain

plugins:
 - serverless-plugin-additional-stacks

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 5
  stage: dev
  region: us-west-1
  versionFunctions: false
  stackTags:
    Tag1 : lti
    Tag2 : lti-launch
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.CONFIG_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "sdb:*"
      Resource: "arn:aws:sdb:${self:provider.region}:*:domain/${self:service}-${opt:stage, self:provider.stage}-LTILaunchUserSimpleDB-*"

  environment:
       LTI_APP_URL: ${self:custom.ltiDashboard-${opt:stage, self:provider.stage}}
       USERID_SIMPLEDB_DOMAIN:
         Ref: LTILaunchUserSimpleDB
       CONFIG_BUCKET: 'ilios-lti-launch-configuration-${opt:stage, self:provider.stage}'

functions:
  dashboard:
    description: Launches the ilios-lti application dashboard
    handler: handler.dashboard
    events:
      - http:
          path: dashboard
          method: post
          integration: lambda-proxy

resources:
  Resources:
    LTILaunchUserSimpleDB:
      Type: "AWS::SDB::Domain"
      Properties:
        Description: LaunchLTI SimpleDB for caching userId values
